# this docker is setting nginx settings

FROM nginx:1.13.6

ENV FLOW_WEB_DIR=/var/www/flow-web
ENV FLOW_WEB_LOG=/var/log/nginx


RUN mkdir -p $FLOW_WEB_DIR \
	&& mkdir -p $FLOW_WEB_LOG

COPY ./target/dist $FLOW_WEB_DIR
COPY ./nginx/default.conf /etc/nginx/conf.d
COPY ./docker/flow-web.sh $FLOW_WEB_DIR

CMD bash $FLOW_WEB_DIR/flow-web.sh && nginx -g 'daemon off;'