# flow.ci agent docker include flow ci agent
# VERSION beta 0.1

# ENV needs to be specified
# - FLOW_ZOOKEEPER_HOST: zookeeper host will be connected to
# - FLOW_AGENT_ZONE: agent working zone
# - FLOW_AGENT_NAME: agent name

FROM flowci/flow.git

# setup agent working dir
ENV FLOW_AGENT_DIR=$HOME/agent
RUN mkdir -p $FLOW_AGENT_DIR

# add agent file
COPY ./target/flow-agent-*.jar $FLOW_AGENT_DIR

WORKDIR $FLOW_AGENT_DIR

CMD java -jar ./flow-agent-*.jar $FLOW_BASE_URL $FLOW_TOKEN