# flow.ci.backend docker includes war of flow.ci api and control center
# VERSION beta 0.1

# The image provides default settings for flow.ci
# if you want to customize flow.ci settings file,
# please mount to /etc/flow.ci to customize  app-api.properties,
# and app-cc.properties in config folder


FROM mysql:5.6

ENV MYSQL_CONF=/etc/mysql/mysql.conf.d

COPY ./mysql/mysqld.cnf $MYSQL_CONF
