# flow.ci.backend docker includes war of flow.ci api and control center
# VERSION beta 0.1

# The image provides default settings for flow.ci
# if you want to customize flow.ci settings file,
# please mount to /etc/flow.ci to customize  app-api.properties,
# and app-cc.properties in config folder


FROM java:8-jre

RUN apt-get update \
	&& apt-get -y install git \
	&& git config --global user.email "flowci@flow.ci" \
	&& git config --global user.name "flowci"
