# flow.ci.backend docker includes war of flow.ci api and control center
# VERSION beta 0.1

# The image provides default settings for flow.ci
# if you want to customize flow.ci settings file,
# please mount to /etc/flow.ci to customize  app-api.properties,
# and app-cc.properties in config folder


FROM flowci/flow.git:latest
FROM flowci/flow.ci.tomcat:latest

# setup flow.ci default environments
ENV FLOW_PLATFORM_DIR=/etc/flow.ci
ENV FLOW_PLATFORM_CONFIG_DIR=/etc/flow.ci/config

RUN mkdir -p $FLOW_PLATFORM_DIR \
	mkdir -p $FLOW_PLATFORM_CONFIG_DIR \
	mkdir -p $FLOW_PLATFORM_DIR/migration

# setup flow.ci default configuration
COPY ./docker/app-cc.properties $FLOW_PLATFORM_CONFIG_DIR
COPY ./docker/app-api.properties $FLOW_PLATFORM_CONFIG_DIR

# config tomcat
COPY ./docker/tomcat-users.xml $CATALINA_HOME/conf

# wait for mysql 
COPY ./docker/flow.ci.backend.cmd.sh $FLOW_PLATFORM_DIR
COPY ./target/migration $FLOW_PLATFORM_DIR/migration

# set wars to tomcat
COPY ./target/flow-control-center.war $CATALINA_HOME/webapps
COPY ./target/flow-api.war $CATALINA_HOME/webapps

WORKDIR $FLOW_PLATFORM_DIR

CMD bash ./flow.ci.backend.cmd.sh catalina.sh run