FROM nginx

ENV FLOW_WEB_DIR=/var/www/flow-web
ENV FLOW_WEB_LOG=/var/log/nginx

# COPY ./dist /usr/share/nginx/html

RUN mkdir -p $FLOW_WEB_DIR
RUN mkdir -p $FLOW_WEB_LOG

COPY ./target/dist $FLOW_WEB_DIR
COPY ./nginx/default.conf /etc/nginx/conf.d
