## Docker-Compose file is used to start flow.ci services

##### Environment Variables #####
## FLOWCI_SERVER_HOST##
## FLOWCI_RABBIT_HOST ##
## FLOWCI_ZOOKEEPER_HOST ##

version: '3.4'

services:
  db:
    image: mongo:3.6
    restart: always
    container_name: flowci-db
    volumes:
      - "db-data:/data/db"
    ports:
      - "27017:27017"
    networks:
      flowci_net:
        ipv4_address: 172.1.3.1

  zk:
    image: zookeeper:3.4
    container_name: flowci-zk
    restart: always
    ports:
      - "2181:2181"
    networks:
      flowci_net:
        ipv4_address: 172.1.3.2

  rabbitmq:
    image: rabbitmq:3-management
    container_name: flowci-rabbitmq
    ports:
      - "5672:5672"
    networks:
      flowci_net:
        ipv4_address: 172.1.3.3

  minio:
    image: minio/minio
    container_name: flowci-minio
    environment:
      MINIO_ACCESS_KEY: $FLOWCI_DEFAULT_MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $FLOWCI_DEFAULT_MINIO_SECRET_KEY
    volumes:
      - "minio-data:/data"
    command: server /data
    networks:
      flowci_net:
        ipv4_address: 172.1.3.4

  core:
    image: flowci/core
    container_name: flowci-core
    ports:
      - "$FLOWCI_SERVER_PORT:8080"
    volumes:
      - "core-ws:/root/.flow.ci"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      FLOWCI_LOG_LEVEL: DEBUG
      FLOWCI_SERVER_URL: $FLOWCI_SERVER_URL
      FLOWCI_DEFAULT_ADMIN_EMAIL: $FLOWCI_DEFAULT_ADMIN_EMAIL
      FLOWCI_DEFAULT_ADMIN_PASSWORD: $FLOWCI_DEFAULT_ADMIN_PASSWORD
      FLOWCI_MONGODB_URI: mongodb://db:27017/flow_ci_db
      FLOWCI_RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      FLOWCI_MINIO_ENDPOINT: http://minio:9000
      FLOWCI_MINIO_KEY: $FLOWCI_DEFAULT_MINIO_ACCESS_KEY
      FLOWCI_MINIO_SECRET: $FLOWCI_DEFAULT_MINIO_SECRET_KEY
      FLOWCI_ZK_HOST: zk
      FLOWCI_AGENT_VOLUMES: $FLOWCI_AGENT_VOLUMES

      # config host for agent
      FLOWCI_RABBIT_HOST: $FLOWCI_RABBIT_HOST
      FLOWCI_ZOOKEEPER_HOST: $FLOWCI_ZOOKEEPER_HOST
    command: [
      "./wait_for_it.sh", 
      "rabbitmq:5672", 
      "-t", "0", 
      "--strict", "--",
      "java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", 
      "-Xms1500m", "-Xmx1500m", "-jar", "flow-ci-core.jar"
    ]
    depends_on:
      - rabbitmq
      - db
      - zk
      - minio
    networks:
      flowci_net:
        ipv4_address: 172.1.2.1

  web:
    image: flowci/web
    container_name: flowci-web
    ports:
      - "$FLOWCI_WEB_PORT:2015"
    environment:
      FLOWCI_SERVER_URL: $FLOWCI_SERVER_URL
    networks:
      flowci_net:
        ipv4_address: 172.1.1.1

volumes:
  core-ws:
    name: flow-ci-ws
  db-data:
    name: flow-ci-db
  minio-data:
    name: flow-ci-minio

networks:
  flowci_net:
    ipam:
      driver: default
      config:
        - subnet: "172.1.0.0/16"