## Docker-Compose file is used to start flow.ci services

version: "3.4"

services:
  db:
    image: mongo:6
    restart: always
    container_name: flowci-db
    volumes:
      - "$FLOWCI_DATABASE_DIR:/data/db"
    ports:
      - "27017:27017"
    entrypoint: ["/usr/bin/mongod", "--port", "27017", "--replSet", "rs0", "--bind_ip_all"]
    networks:
      flowci_net:
        ipv4_address: 172.1.3.1

  db-setup:
    image: flowci/mongosh
    container_name: flowci-db-setup
    depends_on:
      - db
    volumes:
      - ./mongodb:/ws
    entrypoint: "/ws/mongo_init.sh"
    networks:
      flowci_net:
        ipv4_address: 172.1.3.11

  zk:
    image: zookeeper:3.6
    container_name: flowci-zk
    restart: always
    ports:
      - "2181:2181"
    networks:
      flowci_net:
        ipv4_address: 172.1.3.2

  rabbitmq:
    image: rabbitmq:3-management
    container_name: flowci-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      flowci_net:
        ipv4_address: 172.1.3.3

  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-02T10-51-33Z
    container_name: flowci-minio
    restart: always
    environment:
      MINIO_ROOT_USER: $FLOWCI_DEFAULT_MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $FLOWCI_DEFAULT_MINIO_ROOT_PASSWORD
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - "$FLOWCI_DATA_DIR:/data"
    command: "server /data --console-address \":9090\""
    networks:
      flowci_net:
        ipv4_address: 172.1.3.4

  core:
    image: flowci/core
    container_name: flowci-core
    restart: always
    ports:
      - "$FLOWCI_SERVER_PORT:8080"
    volumes:
      - "$FLOWCI_WORKSPACE_DIR:/root/.flow.ci"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      FLOWCI_LOG_LEVEL: DEBUG
      FLOWCI_SERVER_URL: $FLOWCI_SERVER_URL
      FLOWCI_WEB_URL: $FLOWCI_SERVER_URL
      FLOWCI_MONGODB_URI: mongodb://flowci:flowci@db:27017/flow_ci_db?authSource=admin
      FLOWCI_RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      FLOWCI_MINIO_ENDPOINT: http://minio:9000
      FLOWCI_MINIO_KEY: $FLOWCI_DEFAULT_MINIO_ROOT_USER
      FLOWCI_MINIO_SECRET: $FLOWCI_DEFAULT_MINIO_ROOT_PASSWORD
      FLOWCI_ZK_HOST: zk
      FLOWCI_AGENT_VOLUMES: $FLOWCI_AGENT_VOLUMES
    command:
      [
        "./wait_for_it.sh",
        "rabbitmq:5672",
        "-t",
        "0",
        "--strict",
        "--",
        "java",
        "-XX:-UseAdaptiveSizePolicy",
        "-Xms1500m",
        "-Xmx1500m",
        "-Xmn900m",
        "-XX:SurvivorRatio=5",
        "-jar",
        "flowci-core.jar",
      ]
    depends_on:
      - rabbitmq
      - db
      - zk
      - minio
    networks:
      flowci_net:
        ipv4_address: 172.1.2.1

  web:
    image: flowci/web
    container_name: flowci-web
    restart: always
    ports:
      - "$FLOWCI_WEB_PORT:80"
    environment:
      FLOWCI_SERVER_URL: $FLOWCI_SERVER_URL
    networks:
      flowci_net:
        ipv4_address: 172.1.1.1

networks:
  flowci_net:
    ipam:
      driver: default
      config:
        - subnet: "172.1.0.0/16"
