apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowci-minio
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flowci-minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flowci-minio
    spec:
      containers:
        - name: flowci-minio
          image: minio/minio:RELEASE.2021-06-07T21-40-51Z
          env:
            - name: "MINIO_ACCESS_KEY"
              value: "minio"
            - name: "MINIO_SECRET_KEY"
              value: "minio123"
          command: ["minio"]
          args: ["server", "/data"]
          volumeMounts:
            - mountPath: "/data"
              name: data
          ports:
            - name: tcp
              containerPort: 9000
              protocol: TCP
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: flowci-minio-data
