apiVersion: v1
kind: Service
metadata:
  name: flowci-core-service
spec:
  type: {{ .Values.service.core.type }}
  ports:
    - port: {{ .Values.service.core.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: flowci-core
