apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowci-core
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flowci-core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flowci-core
    spec:
      containers:
        - name: flowci-core
          image: flowci/core
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
