# core
apiVersion: v1
kind: Service
metadata:
  name: flowci-core-service
spec:
  type: NodePort
  selector:
    app: flowci-core
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30180

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowci-core-deployment
  labels:
    app: flowci-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowci-core
  template:
    metadata:
      labels:
        app: flowci-core
    spec:
      containers:
        - name: core
          image: flowci/core:dev
          imagePullPolicy: Always
          env:
            - name: FLOWCI_LOG_LEVEL
              value: DEBUG
            - name: FLOWCI_SERVER_URL
              value: http://flowci-core-service:8080
            - name: FLOWCI_MONGODB_URI
              value: mongodb://flowci-db-service:27017/flow_ci_db
            - name: FLOWCI_RABBITMQ_URI
              value: amqp://guest:guest@flowci-mq-service:5672
            - name: FLOWCI_MINIO_ENDPOINT
              value: http://flowci-minio-service:9000
            - name: FLOWCI_MINIO_KEY
              value: minio
            - name: FLOWCI_MINIO_SECRET
              value: minio123
            - name: FLOWCI_ZK_HOST
              value: flowci-zk-service
            - name: FLOWCI_AGENT_IMAGE
              value: flowci/agent
            - name: FLOWCI_AGENT_VOLUMES
              value: "name=pyenv,dest=/ci/python,script=init.sh,image=flowci/pyenv,init=init-pyenv-volume.sh"
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            [
              "./wait_for_it.sh",
              "flowci-mq-service:5672",
              "-t",
              "0",
              "--strict",
              "--",
              "java",
              "-XX:+UnlockExperimentalVMOptions",
              "-XX:+UseCGroupMemoryLimitForHeap",
              "-XX:-UseAdaptiveSizePolicy",
              "-Xms1500m",
              "-Xmx1500m",
              "-Xmn900m",
              "-XX:SurvivorRatio=5",
              "-jar",
              "flow-ci-core.jar",
            ]
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "2Gi"
              cpu: "2000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
