# minio
apiVersion: v1
kind: Service
metadata:
  name: flowci-minio-service
spec:
  selector:
    app: flowci-minio
  ports:
    - protocol: TCP
      port: 9000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowci-minio-deployment
  labels:
    app: flowci-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowci-minio
  template:
    metadata:
      labels:
        app: flowci-minio
    spec:
      volumes:
        - name: data
          hostPath:
            path: /flowci/minio
            type: DirectoryOrCreate
      containers:
        - name: minio
          image: minio/minio:RELEASE.2021-06-07T21-40-51Z
          env:
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"
          args:
            - "server"
            - "/data"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data 
              mountPath: "/data"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "200m"
