apiVersion: v1
kind: Service
metadata:
  name: flowci-web
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: flowci-web
