apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowci-mongodb
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flowci-mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flowci-mongodb
    spec:
      containers:
        - name: flowci-mongodb
          image: mongo:4.2
          volumeMounts:
            - mountPath: "/data/db"
              name: data
          ports:
            - name: tcp
              containerPort: 27017
              protocol: TCP
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: flowci-mongodb-data
