apiVersion: v1
kind: Service
metadata:
  name: flowci-rabbitmq
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: flowci-rabbitmq
